# Copyright (C) 2021-2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
FROM openvino/ubuntu20_runtime:2022.2.0

USER root

RUN dpkg --get-selections | grep -v deinstall | awk '{print $1}' > base_packages.txt

RUN apt-get update && apt-get install -y \
    python3.8 \
    python3.8-venv; \
    rm -rf /var/lib/apt/lists/*;

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 70; \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 70;

RUN apt-get update && apt-get install -y git

RUN python -m pip install --upgrade pip
# Download sources for GPL/LGPL packages
RUN apt-get update; \
    sed -Ei 's/# deb-src /deb-src /' /etc/apt/sources.list && \
    apt-get update && \
    dpkg --get-selections | grep -v deinstall | awk '{print $1}' > all_packages.txt && \
    grep -v -f base_packages.txt all_packages.txt | while read line; do \
    package=$(echo $line); \
    name=(${package//:/ }); \
    grep -l GPL /usr/share/doc/${name[0]}/copyright; \
    exit_status=$?; \
    if [ $exit_status -eq 0 ]; then \
    apt-get source -q --download-only $package;  \
    fi \
    done && \
    echo "Download source for $(ls | wc -l) third-party packages: $(du -sh)"; \
    rm -rf /var/lib/apt/lists/*;

# Installs dependencies required for OpenVINO optimum
COPY requirements_openvino_optimum.txt .
RUN pip install --no-cache-dir -r requirements_openvino_optimum.txt

RUN rm requirements_openvino_optimum.txt

WORKDIR /home/training

RUN chown openvino -R /home/training

USER openvino

ENTRYPOINT ["/bin/bash", "run_qat.sh"]